### PR TITLE
ZATCA specifications Phase two

### PR DESCRIPTION
**Pull request by thaifanisalla**
Generating CSR content, based on parameters 

```php
use Salla\ZATCA\Models\InvoiceSign;

$xmlInvoice = 'xml invoice text';

$certificate = new \Salla\ZATCA\Helpers\Certificate(
            'certificate plain text (base64 decoded)',
            'private key plain text'
);

$certificate->setSecretKey('secret key text');

$invoice = (new InvoiceSign($xmlInvoice, $certificate))->sign();

// invoice Hash: $invoice->getHash()
// invoice signed as XML: $invoice->getInvoice()
// Invoice QR code as base64: $invoice->getQRCode()
```

### CODE REVIEW

**Review by salkhwlani — CHANGES_REQUESTED** [review]

**Comment by thaifanisalla** [comment]
> @thaifanisalla @salkhwlani When we can expect this PR to be merged blush?

as soon...

**Comment by twf-nikhila** [comment]
Are there any steps for using this feature?

**Comment by aneeskhan47** [comment]
@thaifanisalla @salkhwlani Hii, thank you for your great work on this library! 

Is this phase 2 branch completed? i mean can it be used till you guys merge it with main branch?

**Comment by aneesdev** [comment]
@thaifanisalla @salkhwlani Any update on this PR to be merged soon? or at least can we use this branch separately ourselves?

**Comment by aneeskhan47** [comment]
@thaifanisalla @salkhwlani Day **928329** of asking when this phase two PR will be merged 😄

**Comment by salkhwlani** [comment]
Thank you all for waiting, we'll prepare the readme this week and release the new version

**Pull request merged**
